{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "4b30e9ce",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: faker in c:\\users\\dell\\anaconda3\\lib\\site-packages (26.2.0)\n",
      "Requirement already satisfied: python-dateutil>=2.4 in c:\\users\\dell\\anaconda3\\lib\\site-packages (from faker) (2.8.2)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\dell\\anaconda3\\lib\\site-packages (from python-dateutil>=2.4->faker) (1.16.0)\n"
     ]
    }
   ],
   "source": [
    "get_ipython().system('pip install faker')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "62dec976",
   "metadata": {},
   "outputs": [],
   "source": [
    "import random\n",
    "#library for generating numbers\n",
    "import pandas as pd\n",
    "from faker import Faker\n",
    "\n",
    "fake = Faker()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "21e338fd",
   "metadata": {},
   "outputs": [],
   "source": [
    "def generate_employees(num_employees=400):\n",
    "    employees = []\n",
    "    for i in range(num_employees):\n",
    "        Name = fake.name()\n",
    "        Salary = random.randint(5000, 30000)  \n",
    "        #Random salary between 5000 and 30000\n",
    "        Sex = random.choice(['Male', 'Female'])\n",
    "        employees.append({'Id': i+1, 'Name' : Name, 'Salary': Salary, 'Sex': Sex})\n",
    "    return employees\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "30b54ede",
   "metadata": {},
   "outputs": [],
   "source": [
    "def employee_level(employee):\n",
    "    try:        \n",
    "        if 10000 < employee['Salary'] < 20000:\n",
    "            employee['level'] = 'A1'\n",
    "        elif 7500 < employee['Salary'] < 30000 and employee['Sex'] == 'Female':\n",
    "            employee['level'] = 'A5-F'\n",
    "        else:\n",
    "            employee['level'] = 'Unknown'\n",
    "    except Exception as e:\n",
    "        print(f\"Error determining level for worker {employee['Id']}: {e}\")\n",
    "        employee['level'] = 'Error'\n",
    "    return employee\n",
    "\n",
    "employees = generate_employees()\n",
    "\n",
    "employees = [employee_level(employee) for employee in employees]\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "d0818a78",
   "metadata": {},
   "outputs": [],
   "source": [
    "df_employees = pd.DataFrame(employees)\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "2f8c54e5",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Id</th>\n",
       "      <th>Name</th>\n",
       "      <th>Salary</th>\n",
       "      <th>Sex</th>\n",
       "      <th>level</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>1</td>\n",
       "      <td>Angela Howe</td>\n",
       "      <td>6523</td>\n",
       "      <td>Female</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2</td>\n",
       "      <td>Robert Vazquez</td>\n",
       "      <td>13728</td>\n",
       "      <td>Male</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>3</td>\n",
       "      <td>Joanna Pruitt</td>\n",
       "      <td>7114</td>\n",
       "      <td>Female</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>4</td>\n",
       "      <td>George Cunningham</td>\n",
       "      <td>18575</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>5</td>\n",
       "      <td>Joshua Smith</td>\n",
       "      <td>25127</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>6</td>\n",
       "      <td>Michael Taylor</td>\n",
       "      <td>27830</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>7</td>\n",
       "      <td>Steven Sellers</td>\n",
       "      <td>28984</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>8</td>\n",
       "      <td>Yesenia Harding</td>\n",
       "      <td>20206</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>9</td>\n",
       "      <td>Shari Bush</td>\n",
       "      <td>11477</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>10</td>\n",
       "      <td>John Young</td>\n",
       "      <td>12376</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>11</td>\n",
       "      <td>Stephanie Ryan</td>\n",
       "      <td>7722</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>12</td>\n",
       "      <td>David Bailey</td>\n",
       "      <td>24056</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>13</td>\n",
       "      <td>Laura Diaz</td>\n",
       "      <td>11382</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>14</td>\n",
       "      <td>Justin Hart</td>\n",
       "      <td>16523</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>15</td>\n",
       "      <td>Anthony Watkins</td>\n",
       "      <td>16125</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>16</td>\n",
       "      <td>Katie Carter</td>\n",
       "      <td>6206</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>17</td>\n",
       "      <td>Carol Burke</td>\n",
       "      <td>13597</td>\n",
       "      <td>Male</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>18</td>\n",
       "      <td>Scott Morales</td>\n",
       "      <td>13837</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>19</td>\n",
       "      <td>Alan Douglas</td>\n",
       "      <td>23224</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>20</td>\n",
       "      <td>Zachary Clark</td>\n",
       "      <td>6219</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>20</th>\n",
       "      <td>21</td>\n",
       "      <td>Patrick Chavez</td>\n",
       "      <td>27162</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>21</th>\n",
       "      <td>22</td>\n",
       "      <td>Jeffrey Mcdaniel</td>\n",
       "      <td>21788</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>23</td>\n",
       "      <td>Scott Cowan</td>\n",
       "      <td>22828</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>23</th>\n",
       "      <td>24</td>\n",
       "      <td>Jennifer Alvarez</td>\n",
       "      <td>22080</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>24</th>\n",
       "      <td>25</td>\n",
       "      <td>Tina Ruiz</td>\n",
       "      <td>6525</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25</th>\n",
       "      <td>26</td>\n",
       "      <td>Mrs. Isabella Jones</td>\n",
       "      <td>15777</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>26</th>\n",
       "      <td>27</td>\n",
       "      <td>Kenneth Tyler</td>\n",
       "      <td>18022</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>27</th>\n",
       "      <td>28</td>\n",
       "      <td>Carol Henderson</td>\n",
       "      <td>22952</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>28</th>\n",
       "      <td>29</td>\n",
       "      <td>Angela Steele</td>\n",
       "      <td>7467</td>\n",
       "      <td>Female</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>29</th>\n",
       "      <td>30</td>\n",
       "      <td>Kenneth Adams</td>\n",
       "      <td>18803</td>\n",
       "      <td>Male</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>30</th>\n",
       "      <td>31</td>\n",
       "      <td>Eric Mitchell</td>\n",
       "      <td>9039</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>31</th>\n",
       "      <td>32</td>\n",
       "      <td>Crystal Morris</td>\n",
       "      <td>21842</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>32</th>\n",
       "      <td>33</td>\n",
       "      <td>Bruce Chavez</td>\n",
       "      <td>9097</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>33</th>\n",
       "      <td>34</td>\n",
       "      <td>Alex Jones</td>\n",
       "      <td>9770</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>34</th>\n",
       "      <td>35</td>\n",
       "      <td>Savannah Nguyen</td>\n",
       "      <td>25136</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>35</th>\n",
       "      <td>36</td>\n",
       "      <td>Amber Hill</td>\n",
       "      <td>11426</td>\n",
       "      <td>Male</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>36</th>\n",
       "      <td>37</td>\n",
       "      <td>Justin Mitchell</td>\n",
       "      <td>16013</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>37</th>\n",
       "      <td>38</td>\n",
       "      <td>Jamie Leon</td>\n",
       "      <td>24416</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>38</th>\n",
       "      <td>39</td>\n",
       "      <td>Edward Nguyen Jr.</td>\n",
       "      <td>21535</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>39</th>\n",
       "      <td>40</td>\n",
       "      <td>Ricardo Miller</td>\n",
       "      <td>15575</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>40</th>\n",
       "      <td>41</td>\n",
       "      <td>Wayne Moore</td>\n",
       "      <td>27497</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>41</th>\n",
       "      <td>42</td>\n",
       "      <td>Alexa Thomas</td>\n",
       "      <td>10884</td>\n",
       "      <td>Male</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>42</th>\n",
       "      <td>43</td>\n",
       "      <td>John Graves</td>\n",
       "      <td>24955</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>44</td>\n",
       "      <td>Aaron Ellis</td>\n",
       "      <td>27218</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>44</th>\n",
       "      <td>45</td>\n",
       "      <td>Joseph Kennedy</td>\n",
       "      <td>19143</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>45</th>\n",
       "      <td>46</td>\n",
       "      <td>Tristan Smith</td>\n",
       "      <td>26984</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>46</th>\n",
       "      <td>47</td>\n",
       "      <td>Brittany Mcintosh</td>\n",
       "      <td>20730</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>47</th>\n",
       "      <td>48</td>\n",
       "      <td>Joseph Zimmerman</td>\n",
       "      <td>11717</td>\n",
       "      <td>Male</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>48</th>\n",
       "      <td>49</td>\n",
       "      <td>Sean Munoz</td>\n",
       "      <td>16163</td>\n",
       "      <td>Male</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>50</td>\n",
       "      <td>Kenneth Stevens</td>\n",
       "      <td>12872</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50</th>\n",
       "      <td>51</td>\n",
       "      <td>Daniel Garcia</td>\n",
       "      <td>10996</td>\n",
       "      <td>Male</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>51</th>\n",
       "      <td>52</td>\n",
       "      <td>Stephen King</td>\n",
       "      <td>12670</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>52</th>\n",
       "      <td>53</td>\n",
       "      <td>Miss Lisa Bishop</td>\n",
       "      <td>14609</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>53</th>\n",
       "      <td>54</td>\n",
       "      <td>Carmen Montgomery</td>\n",
       "      <td>20441</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>54</th>\n",
       "      <td>55</td>\n",
       "      <td>Jacqueline Morris</td>\n",
       "      <td>8817</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>55</th>\n",
       "      <td>56</td>\n",
       "      <td>Marc Chapman</td>\n",
       "      <td>9643</td>\n",
       "      <td>Female</td>\n",
       "      <td>A5-F</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>56</th>\n",
       "      <td>57</td>\n",
       "      <td>Joshua Wells</td>\n",
       "      <td>12751</td>\n",
       "      <td>Female</td>\n",
       "      <td>A1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>57</th>\n",
       "      <td>58</td>\n",
       "      <td>Maureen Wallace</td>\n",
       "      <td>28976</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>58</th>\n",
       "      <td>59</td>\n",
       "      <td>Shawn Arnold</td>\n",
       "      <td>5655</td>\n",
       "      <td>Female</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>59</th>\n",
       "      <td>60</td>\n",
       "      <td>Robert Faulkner</td>\n",
       "      <td>23014</td>\n",
       "      <td>Male</td>\n",
       "      <td>Unknown</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "    Id                 Name  Salary     Sex    level\n",
       "0    1          Angela Howe    6523  Female  Unknown\n",
       "1    2       Robert Vazquez   13728    Male       A1\n",
       "2    3        Joanna Pruitt    7114  Female  Unknown\n",
       "3    4    George Cunningham   18575  Female       A1\n",
       "4    5         Joshua Smith   25127  Female     A5-F\n",
       "5    6       Michael Taylor   27830    Male  Unknown\n",
       "6    7       Steven Sellers   28984    Male  Unknown\n",
       "7    8      Yesenia Harding   20206  Female     A5-F\n",
       "8    9           Shari Bush   11477  Female       A1\n",
       "9   10           John Young   12376  Female       A1\n",
       "10  11       Stephanie Ryan    7722    Male  Unknown\n",
       "11  12         David Bailey   24056  Female     A5-F\n",
       "12  13           Laura Diaz   11382  Female       A1\n",
       "13  14          Justin Hart   16523  Female       A1\n",
       "14  15      Anthony Watkins   16125  Female       A1\n",
       "15  16         Katie Carter    6206    Male  Unknown\n",
       "16  17          Carol Burke   13597    Male       A1\n",
       "17  18        Scott Morales   13837  Female       A1\n",
       "18  19         Alan Douglas   23224    Male  Unknown\n",
       "19  20        Zachary Clark    6219    Male  Unknown\n",
       "20  21       Patrick Chavez   27162  Female     A5-F\n",
       "21  22     Jeffrey Mcdaniel   21788  Female     A5-F\n",
       "22  23          Scott Cowan   22828  Female     A5-F\n",
       "23  24     Jennifer Alvarez   22080    Male  Unknown\n",
       "24  25            Tina Ruiz    6525    Male  Unknown\n",
       "25  26  Mrs. Isabella Jones   15777  Female       A1\n",
       "26  27        Kenneth Tyler   18022  Female       A1\n",
       "27  28      Carol Henderson   22952    Male  Unknown\n",
       "28  29        Angela Steele    7467  Female  Unknown\n",
       "29  30        Kenneth Adams   18803    Male       A1\n",
       "30  31        Eric Mitchell    9039  Female     A5-F\n",
       "31  32       Crystal Morris   21842  Female     A5-F\n",
       "32  33         Bruce Chavez    9097    Male  Unknown\n",
       "33  34           Alex Jones    9770  Female     A5-F\n",
       "34  35      Savannah Nguyen   25136    Male  Unknown\n",
       "35  36           Amber Hill   11426    Male       A1\n",
       "36  37      Justin Mitchell   16013  Female       A1\n",
       "37  38           Jamie Leon   24416  Female     A5-F\n",
       "38  39    Edward Nguyen Jr.   21535  Female     A5-F\n",
       "39  40       Ricardo Miller   15575  Female       A1\n",
       "40  41          Wayne Moore   27497  Female     A5-F\n",
       "41  42         Alexa Thomas   10884    Male       A1\n",
       "42  43          John Graves   24955  Female     A5-F\n",
       "43  44          Aaron Ellis   27218    Male  Unknown\n",
       "44  45       Joseph Kennedy   19143  Female       A1\n",
       "45  46        Tristan Smith   26984  Female     A5-F\n",
       "46  47    Brittany Mcintosh   20730    Male  Unknown\n",
       "47  48     Joseph Zimmerman   11717    Male       A1\n",
       "48  49           Sean Munoz   16163    Male       A1\n",
       "49  50      Kenneth Stevens   12872  Female       A1\n",
       "50  51        Daniel Garcia   10996    Male       A1\n",
       "51  52         Stephen King   12670  Female       A1\n",
       "52  53     Miss Lisa Bishop   14609  Female       A1\n",
       "53  54    Carmen Montgomery   20441  Female     A5-F\n",
       "54  55    Jacqueline Morris    8817    Male  Unknown\n",
       "55  56         Marc Chapman    9643  Female     A5-F\n",
       "56  57         Joshua Wells   12751  Female       A1\n",
       "57  58      Maureen Wallace   28976    Male  Unknown\n",
       "58  59         Shawn Arnold    5655  Female  Unknown\n",
       "59  60      Robert Faulkner   23014    Male  Unknown"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df_employees.head(60)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "aeebcf2e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
